title: Nicoly Welter # your name (or website title) here
logo: "/images/DSC_5532.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in Civil and Environmental Engineering at the University of Rhode Island
  <br><br>
  Department of Civil and Environmental Engineering
  <br><br>
  <a href="https://scholar.google.com/citations?user=bBUQWV0AAAAJ&hl=en">View My Google Scholar Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
